// ============================================
// VERTALINGEN NEDERLANDS / ENGELS
// ============================================

export type Taal = 'nl' | 'en';

export interface Vertalingen {
  // Navigatie
  nav: {
    dashboard: string;
    thisWeek: string;
    allTasks: string;
    cultivationTasks: string;
    harvestList: string;
    instructions: string;
    messages: string;
    gardenMaps: string;
    import: string;
    settings: string;
    taskManagement: string;
  };

  // Formulier labels
  form: {
    description: string;
    descriptionRequired: string;
    descriptionPlaceholder: string;
    section: string;
    noSection: string;
    bed: string;
    noBed: string;
    taskType: string;
    priority: string;
    status: string;
    deadline: string;
    deadlineRepeat: string;
    startDate: string;
    notes: string;
    notesPlaceholder: string;
    autoGenerated: string;
    communityNotes: string;
    completedBy: string;
    completedOn: string;
    cancel: string;
    save: string;
    quickTask: string;
    newTask: string;
    editTask: string;
    createdAt: string;
    weeklyRecurring: string;
    repeatUntil: string;
    weekly: string;
    doneThisWeek: string;
    undoThisWeek: string;
  };

  // Rollen
  roles: {
    community: string;
    committee: string;
    committeeMode: string;
    backToCommunity: string;
    enterPin: string;
    incorrectPin: string;
    login: string;
    cancel: string;
  };

  // Dashboard
  dashboard: {
    title: string;
    welcome: string;
    week: string;
    openTasks: string;
    inProgress: string;
    urgent: string;
    completed: string;
    thisWeek: string;
    overdue: string;
    beds: string;
    crops: string;
    sections: string;
    quickActions: string;
    generateTasks: string;
    cleanupOldTasks: string;
    importData: string;
    tasksThisWeek: string;
    viewWeekOverview: string;
    noBeds: string;
    noBedData: string;
    bedDetails: string;
    yearPlanning: string;
    cropInfo: string;
    noCrops: string;
    noActions: string;
    size: string;
    dimensions: string;
    sections_label: string;
    planForBed: string;
    remarks: string;
    part: string;
    begin: string;
    middle: string;
    end: string;
  };

  // Taken
  tasks: {
    title: string;
    addTask: string;
    editTask: string;
    description: string;
    section: string;
    bed: string;
    type: string;
    priority: string;
    status: string;
    deadline: string;
    comment: string;
    completedBy: string;
    completedOn: string;
    save: string;
    delete: string;
    cancel: string;
    markComplete: string;
    yourName: string;
    workingOnTask: string;
    startWorking: string;
    stopWorking: string;
    workingBy: string;
    enterYourName: string;
    // Types
    types: {
      sowing: string;
      planting: string;
      harvesting: string;
      maintenance: string;
      other: string;
    };
    // Prioriteiten
    priorities: {
      high: string;
      normal: string;
      low: string;
    };
    // Statussen
    statuses: {
      open: string;
      inProgress: string;
      completed: string;
    };
  };

  // Oogstlijst
  harvest: {
    title: string;
    addItem: string;
    editItem: string;
    crop: string;
    category: string;
    amountPerPerson: string;
    primaryLocation: string;
    secondaryLocation: string;
    tertiaryLocation: string;
    harvestMethod: string;
    details: string;
    status: string;
    harvestCompletely: string;
    week: string;
    registerHarvest: string;
    whoAreYou: string;
    duplicateToWeek: string;
    importFromCsv: string;
    suggestions: string;
    suggestionsDescription: string;
    noSuggestions: string;
    // Statussen
    statuses: {
      available: string;
      check: string;
      empty: string;
      reserved: string;
    };
    // Categorieën
    categories: {
      vegetables: string;
      herbs: string;
    };
  };

  // Signaleringen / Berichten
  messages: {
    title: string;
    newMessage: string;
    type: string;
    message: string;
    section: string;
    bed: string;
    yourName: string;
    send: string;
    reply: string;
    markSeen: string;
    markHandled: string;
    // Types
    types: {
      problem: string;
      question: string;
      suggestion: string;
      compliment: string;
    };
    // Statussen
    statuses: {
      new: string;
      seen: string;
      handled: string;
    };
  };

  // Weekoverzicht
  weekOverview: {
    title: string;
    tasksThisWeek: string;
    harvestThisWeek: string;
    noTasks: string;
    noHarvest: string;
    editGroupTitle: string;
    customTitle: string;
    groupNote: string;
    groupNotePlaceholder: string;
    saveOverride: string;
    resetOverride: string;
    cancelEdit: string;
    titleCustomized: string;
  };

  // Import
  import: {
    title: string;
    beds: string;
    crops: string;
    cultivationPlan: string;
    importBeds: string;
    importCrops: string;
    importCultivationPlan: string;
    csvFormat: string;
    dragOrClick: string;
    importSuccess: string;
    importError: string;
  };

  // Instellingen
  settings: {
    title: string;
    language: string;
    dutch: string;
    english: string;
    dataManagement: string;
    exportData: string;
    importData: string;
    clearData: string;
    clearDataConfirm: string;
  };

  // Filters
  filters: {
    crop: string;
    allCrops: string;
    source: string;
    allSources: string;
    fromCultivationPlan: string;
    addedByCommittee: string;
    moreFilters: string;
    resetFilters: string;
    activeFilters: string;
    searchPlaceholder: string;
    searchCrop: string;
    noCropsFound: string;
    selectCrop: string;
  };

  // Algemeen
  common: {
    all: string;
    loading: string;
    error: string;
    success: string;
    warning: string;
    info: string;
    save: string;
    cancel: string;
    delete: string;
    edit: string;
    add: string;
    close: string;
    confirm: string;
    yes: string;
    no: string;
    search: string;
    filter: string;
    sort: string;
    noData: string;
    dataStatus: string;
    openTasks: string;
  };

  // Maanden
  months: {
    jan: string;
    feb: string;
    mar: string;
    apr: string;
    may: string;
    jun: string;
    jul: string;
    aug: string;
    sep: string;
    oct: string;
    nov: string;
    dec: string;
  };

  // Secties
  sections: Record<string, string>;
}

// Nederlandse vertalingen
export const nl: Vertalingen = {
  nav: {
    dashboard: 'Dashboard',
    thisWeek: 'Deze Week',
    allTasks: 'Alle Taken',
    cultivationTasks: 'Teeltplan Taken',
    harvestList: 'Oogstlijst',
    instructions: 'Instructies',
    messages: 'Berichten',
    gardenMaps: 'Plattegronden',
    import: 'Importeren',
    settings: 'Instellingen',
    taskManagement: 'Community Tuin Planner',
  },

  form: {
    description: 'Beschrijving',
    descriptionRequired: 'Beschrijving *',
    descriptionPlaceholder: 'Wat moet er gedaan worden?',
    section: 'Sectie',
    noSection: 'Geen sectie',
    bed: 'Bed',
    noBed: 'Geen bed',
    taskType: 'Type taak',
    priority: 'Prioriteit',
    status: 'Status',
    deadline: 'Deadline',
    deadlineRepeat: 'Deadline / herhalen tot',
    startDate: 'Startdatum',
    notes: 'Notities / Commentaar',
    notesPlaceholder: 'Optionele notities...',
    autoGenerated: 'Automatisch gegenereerd voor',
    communityNotes: 'Notities van community',
    completedBy: 'Afgerond door',
    completedOn: 'op',
    cancel: 'Annuleren',
    save: 'Opslaan',
    quickTask: 'Snelle taak',
    newTask: 'Nieuwe taak',
    editTask: 'Taak bewerken',
    createdAt: 'Aangemaakt',
    weeklyRecurring: 'Wekelijks herhalend',
    repeatUntil: 'Herhalen tot',
    weekly: 'Wekelijks',
    doneThisWeek: 'Klaar deze week',
    undoThisWeek: 'Toch niet klaar',
  },

  roles: {
    community: 'Community',
    committee: 'Commissie',
    committeeMode: 'Commissie modus',
    backToCommunity: 'Terug naar community modus',
    enterPin: 'Voer de PIN in',
    incorrectPin: 'Onjuiste PIN',
    login: 'Inloggen',
    cancel: 'Annuleren',
  },

  dashboard: {
    title: 'Dashboard',
    welcome: 'Welkom bij TuinPlanner',
    week: 'Week',
    openTasks: 'Open taken',
    inProgress: 'In uitvoering',
    urgent: 'Urgent',
    completed: 'Afgerond',
    thisWeek: 'Deze Week',
    overdue: 'Te Laat',
    beds: 'Bedden',
    crops: 'Gewassen',
    sections: 'Secties',
    quickActions: 'Snelle Acties',
    generateTasks: 'Taken genereren',
    cleanupOldTasks: 'Oude taken opruimen',
    importData: 'Data importeren',
    tasksThisWeek: 'Taken deze week',
    viewWeekOverview: 'Bekijk het weekoverzicht',
    noBeds: 'Geen bedden geladen',
    noBedData: 'Importeer bedden via de Importeren tab om te beginnen.',
    bedDetails: 'Bed',
    yearPlanning: 'Jaarplanning',
    cropInfo: 'Gewassen',
    noCrops: 'Geen gewassen gepland voor dit bed',
    noActions: 'Geen acties gepland voor dit bed',
    size: 'Grootte',
    dimensions: 'Afmetingen',
    sections_label: 'Vakken',
    planForBed: 'Plan voor dit bed',
    remarks: 'Opmerkingen',
    part: 'Deel',
    begin: 'Begin',
    middle: 'Midden',
    end: 'Eind',
  },

  tasks: {
    title: 'Taken',
    addTask: 'Taak toevoegen',
    editTask: 'Taak bewerken',
    description: 'Beschrijving',
    section: 'Sectie',
    bed: 'Bed',
    type: 'Type',
    priority: 'Prioriteit',
    status: 'Status',
    deadline: 'Deadline',
    comment: 'Opmerking',
    completedBy: 'Afgerond door',
    completedOn: 'Afgerond op',
    save: 'Opslaan',
    delete: 'Verwijderen',
    cancel: 'Annuleren',
    markComplete: 'Markeer als afgerond',
    yourName: 'Je naam',
    workingOnTask: 'Bezig met taak',
    startWorking: 'Ik ga hiermee aan de slag',
    stopWorking: 'Ik stop hiermee',
    workingBy: 'Bezig door',
    enterYourName: 'Vul je naam in',
    types: {
      sowing: 'Zaaien',
      planting: 'Planten',
      harvesting: 'Oogsten',
      maintenance: 'Onderhoud',
      other: 'Overig',
    },
    priorities: {
      high: 'Hoog',
      normal: 'Normaal',
      low: 'Laag',
    },
    statuses: {
      open: 'Open',
      inProgress: 'In uitvoering',
      completed: 'Afgerond',
    },
  },

  harvest: {
    title: 'Oogstlijst',
    addItem: 'Item toevoegen',
    editItem: 'Item bewerken',
    crop: 'Gewas',
    category: 'Categorie',
    amountPerPerson: 'Hoeveelheid p.p.',
    primaryLocation: 'Primaire locatie',
    secondaryLocation: 'Secundaire locatie',
    tertiaryLocation: 'Tertiaire locatie',
    harvestMethod: 'Oogstmethode',
    details: 'Bijzonderheden',
    status: 'Status',
    harvestCompletely: 'Leeg oogsten',
    week: 'Week',
    registerHarvest: 'Oogst registreren',
    whoAreYou: 'Wie ben je?',
    duplicateToWeek: 'Dupliceer naar week',
    importFromCsv: 'Importeer uit CSV',
    suggestions: 'Suggesties',
    suggestionsDescription: 'Gewassen die nu geoogst kunnen worden volgens het teeltplan',
    noSuggestions: 'Geen suggesties beschikbaar',
    statuses: {
      available: 'Beschikbaar',
      check: 'Controleren',
      empty: 'Op',
      reserved: 'Gereserveerd',
    },
    categories: {
      vegetables: 'Groenten',
      herbs: 'Kruiden',
    },
  },

  messages: {
    title: 'Berichten',
    newMessage: 'Nieuw bericht',
    type: 'Type',
    message: 'Bericht',
    section: 'Sectie',
    bed: 'Bed',
    yourName: 'Je naam',
    send: 'Versturen',
    reply: 'Reageren',
    markSeen: 'Markeer als gezien',
    markHandled: 'Markeer als afgehandeld',
    types: {
      problem: 'Probleem',
      question: 'Vraag',
      suggestion: 'Suggestie',
      compliment: 'Compliment',
    },
    statuses: {
      new: 'Nieuw',
      seen: 'Gezien',
      handled: 'Afgehandeld',
    },
  },

  weekOverview: {
    title: 'Weekoverzicht',
    tasksThisWeek: 'Taken deze week',
    harvestThisWeek: 'Oogst deze week',
    noTasks: 'Geen taken deze week',
    noHarvest: 'Geen oogst deze week',
    editGroupTitle: 'Groep bewerken',
    customTitle: 'Aangepaste titel',
    groupNote: 'Notitie',
    groupNotePlaceholder: 'Notitie voor deze groep...',
    saveOverride: 'Opslaan',
    resetOverride: 'Herstellen',
    cancelEdit: 'Annuleren',
    titleCustomized: 'Aangepast',
  },

  import: {
    title: 'Importeren',
    beds: 'Bedden',
    crops: 'Gewassen',
    cultivationPlan: 'Teeltplan',
    importBeds: 'Bedden importeren',
    importCrops: 'Gewassen importeren',
    importCultivationPlan: 'Teeltplan importeren',
    csvFormat: 'CSV formaat',
    dragOrClick: 'Sleep een bestand of klik om te selecteren',
    importSuccess: 'Import succesvol',
    importError: 'Import mislukt',
  },

  settings: {
    title: 'Instellingen',
    language: 'Taal',
    dutch: 'Nederlands',
    english: 'Engels',
    dataManagement: 'Data beheer',
    exportData: 'Data exporteren',
    importData: 'Data importeren',
    clearData: 'Data wissen',
    clearDataConfirm: 'Weet je zeker dat je alle data wilt wissen?',
  },

  filters: {
    crop: 'Gewas',
    allCrops: 'Alle gewassen',
    source: 'Bron',
    allSources: 'Alle bronnen',
    fromCultivationPlan: 'Uit teeltplan',
    addedByCommittee: 'Door commissie',
    moreFilters: 'Meer filters',
    resetFilters: 'Reset filters',
    activeFilters: 'Actieve filters',
    searchPlaceholder: 'Zoek op taak of gewas...',
    searchCrop: 'Zoek gewas...',
    noCropsFound: 'Geen gewassen gevonden',
    selectCrop: 'Selecteer gewas',
  },

  common: {
    all: 'Alle',
    loading: 'Laden...',
    error: 'Fout',
    success: 'Succes',
    warning: 'Waarschuwing',
    info: 'Info',
    save: 'Opslaan',
    cancel: 'Annuleren',
    delete: 'Verwijderen',
    edit: 'Bewerken',
    add: 'Toevoegen',
    close: 'Sluiten',
    confirm: 'Bevestigen',
    yes: 'Ja',
    no: 'Nee',
    search: 'Zoeken',
    filter: 'Filter',
    sort: 'Sorteren',
    noData: 'Geen data',
    dataStatus: 'Data status',
    openTasks: 'open taken',
  },

  months: {
    jan: 'Januari',
    feb: 'Februari',
    mar: 'Maart',
    apr: 'April',
    may: 'Mei',
    jun: 'Juni',
    jul: 'Juli',
    aug: 'Augustus',
    sep: 'September',
    oct: 'Oktober',
    nov: 'November',
    dec: 'December',
  },

  sections: {
    A: 'Sectie A',
    B: 'Sectie B',
    C: 'Sectie C',
    D: 'Sectie D',
    E: 'Sectie E',
    Kas: 'Kas',
  },
};

// Engelse vertalingen
export const en: Vertalingen = {
  nav: {
    dashboard: 'Dashboard',
    thisWeek: 'This Week',
    allTasks: 'All Tasks',
    cultivationTasks: 'Cultivation Tasks',
    harvestList: 'Harvest List',
    instructions: 'Instructions',
    messages: 'Messages',
    gardenMaps: 'Garden Maps',
    import: 'Import',
    settings: 'Settings',
    taskManagement: 'Allotment Task Management',
  },

  form: {
    description: 'Description',
    descriptionRequired: 'Description *',
    descriptionPlaceholder: 'What needs to be done?',
    section: 'Section',
    noSection: 'No section',
    bed: 'Bed',
    noBed: 'No bed',
    taskType: 'Task type',
    priority: 'Priority',
    status: 'Status',
    deadline: 'Deadline',
    deadlineRepeat: 'Deadline / repeat until',
    startDate: 'Start date',
    notes: 'Notes / Comments',
    notesPlaceholder: 'Optional notes...',
    autoGenerated: 'Auto-generated for',
    communityNotes: 'Notes from community',
    completedBy: 'Completed by',
    completedOn: 'on',
    cancel: 'Cancel',
    save: 'Save',
    quickTask: 'Quick task',
    newTask: 'New task',
    editTask: 'Edit task',
    createdAt: 'Created',
    weeklyRecurring: 'Weekly recurring',
    repeatUntil: 'Repeat until',
    weekly: 'Weekly',
    doneThisWeek: 'Done this week',
    undoThisWeek: 'Undo completed',
  },

  roles: {
    community: 'Community',
    committee: 'Committee',
    committeeMode: 'Committee mode',
    backToCommunity: 'Back to community mode',
    enterPin: 'Enter PIN',
    incorrectPin: 'Incorrect PIN',
    login: 'Login',
    cancel: 'Cancel',
  },

  dashboard: {
    title: 'Dashboard',
    welcome: 'Welcome to TuinPlanner',
    week: 'Week',
    openTasks: 'Open tasks',
    inProgress: 'In progress',
    urgent: 'Urgent',
    completed: 'Completed',
    thisWeek: 'This Week',
    overdue: 'Overdue',
    beds: 'Beds',
    crops: 'Crops',
    sections: 'Sections',
    quickActions: 'Quick Actions',
    generateTasks: 'Generate tasks',
    cleanupOldTasks: 'Clean up old tasks',
    importData: 'Import data',
    tasksThisWeek: 'Tasks this week',
    viewWeekOverview: 'View week overview',
    noBeds: 'No beds loaded',
    noBedData: 'Import beds via the Import tab to get started.',
    bedDetails: 'Bed',
    yearPlanning: 'Year planning',
    cropInfo: 'Crops',
    noCrops: 'No crops planned for this bed',
    noActions: 'No actions planned for this bed',
    size: 'Size',
    dimensions: 'Dimensions',
    sections_label: 'Sections',
    planForBed: 'Plan for this bed',
    remarks: 'Remarks',
    part: 'Part',
    begin: 'Begin',
    middle: 'Middle',
    end: 'End',
  },

  tasks: {
    title: 'Tasks',
    addTask: 'Add task',
    editTask: 'Edit task',
    description: 'Description',
    section: 'Section',
    bed: 'Bed',
    type: 'Type',
    priority: 'Priority',
    status: 'Status',
    deadline: 'Deadline',
    comment: 'Comment',
    completedBy: 'Completed by',
    completedOn: 'Completed on',
    save: 'Save',
    delete: 'Delete',
    cancel: 'Cancel',
    markComplete: 'Mark as complete',
    yourName: 'Your name',
    workingOnTask: 'Working on task',
    startWorking: 'I will work on this',
    stopWorking: 'I stop working on this',
    workingBy: 'Being worked on by',
    enterYourName: 'Enter your name',
    types: {
      sowing: 'Sowing',
      planting: 'Planting',
      harvesting: 'Harvesting',
      maintenance: 'Maintenance',
      other: 'Other',
    },
    priorities: {
      high: 'High',
      normal: 'Normal',
      low: 'Low',
    },
    statuses: {
      open: 'Open',
      inProgress: 'In progress',
      completed: 'Completed',
    },
  },

  harvest: {
    title: 'Harvest List',
    addItem: 'Add item',
    editItem: 'Edit item',
    crop: 'Crop',
    category: 'Category',
    amountPerPerson: 'Amount per person',
    primaryLocation: 'Primary location',
    secondaryLocation: 'Secondary location',
    tertiaryLocation: 'Tertiary location',
    harvestMethod: 'Harvest method',
    details: 'Details',
    status: 'Status',
    harvestCompletely: 'Harvest completely',
    week: 'Week',
    registerHarvest: 'Register harvest',
    whoAreYou: 'Who are you?',
    duplicateToWeek: 'Duplicate to week',
    importFromCsv: 'Import from CSV',
    suggestions: 'Suggestions',
    suggestionsDescription: 'Crops that can be harvested now according to the cultivation plan',
    noSuggestions: 'No suggestions available',
    statuses: {
      available: 'Available',
      check: 'Check',
      empty: 'Empty',
      reserved: 'Reserved',
    },
    categories: {
      vegetables: 'Vegetables',
      herbs: 'Herbs',
    },
  },

  messages: {
    title: 'Messages',
    newMessage: 'New message',
    type: 'Type',
    message: 'Message',
    section: 'Section',
    bed: 'Bed',
    yourName: 'Your name',
    send: 'Send',
    reply: 'Reply',
    markSeen: 'Mark as seen',
    markHandled: 'Mark as handled',
    types: {
      problem: 'Problem',
      question: 'Question',
      suggestion: 'Suggestion',
      compliment: 'Compliment',
    },
    statuses: {
      new: 'New',
      seen: 'Seen',
      handled: 'Handled',
    },
  },

  weekOverview: {
    title: 'Week Overview',
    tasksThisWeek: 'Tasks this week',
    harvestThisWeek: 'Harvest this week',
    noTasks: 'No tasks this week',
    noHarvest: 'No harvest this week',
    editGroupTitle: 'Edit group',
    customTitle: 'Custom title',
    groupNote: 'Note',
    groupNotePlaceholder: 'Note for this group...',
    saveOverride: 'Save',
    resetOverride: 'Reset',
    cancelEdit: 'Cancel',
    titleCustomized: 'Customized',
  },

  import: {
    title: 'Import',
    beds: 'Beds',
    crops: 'Crops',
    cultivationPlan: 'Cultivation Plan',
    importBeds: 'Import beds',
    importCrops: 'Import crops',
    importCultivationPlan: 'Import cultivation plan',
    csvFormat: 'CSV format',
    dragOrClick: 'Drag a file or click to select',
    importSuccess: 'Import successful',
    importError: 'Import failed',
  },

  settings: {
    title: 'Settings',
    language: 'Language',
    dutch: 'Dutch',
    english: 'English',
    dataManagement: 'Data management',
    exportData: 'Export data',
    importData: 'Import data',
    clearData: 'Clear data',
    clearDataConfirm: 'Are you sure you want to clear all data?',
  },

  filters: {
    crop: 'Crop',
    allCrops: 'All crops',
    source: 'Source',
    allSources: 'All sources',
    fromCultivationPlan: 'From cultivation plan',
    addedByCommittee: 'Added by committee',
    moreFilters: 'More filters',
    resetFilters: 'Reset filters',
    activeFilters: 'Active filters',
    searchPlaceholder: 'Search tasks or crops...',
    searchCrop: 'Search crop...',
    noCropsFound: 'No crops found',
    selectCrop: 'Select crop',
  },

  common: {
    all: 'All',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    info: 'Info',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    close: 'Close',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    search: 'Search',
    filter: 'Filter',
    sort: 'Sort',
    noData: 'No data',
    dataStatus: 'Data status',
    openTasks: 'open tasks',
  },

  months: {
    jan: 'January',
    feb: 'February',
    mar: 'March',
    apr: 'April',
    may: 'May',
    jun: 'June',
    jul: 'July',
    aug: 'August',
    sep: 'September',
    oct: 'October',
    nov: 'November',
    dec: 'December',
  },

  sections: {
    A: 'Section A',
    B: 'Section B',
    C: 'Section C',
    D: 'Section D',
    E: 'Section E',
    Kas: 'Greenhouse',
  },
};

// Vertaling ophalen op basis van taal
export const translations: Record<Taal, Vertalingen> = {
  nl,
  en,
};
